name: Deploy to Vercel

on:
  push:
    branches:
      - main  # Change this to your main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install mkdocs-material
        # Add any other dependencies your project may require

    - name: Build site
      run: |
        mkdocs build

    - name: Deploy to Vercel
      uses: vercel/vercel@v21
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}  # Make sure to set VERCEL_TOKEN as a secret in your GitHub repository
        vercel-org-id: YOUR_ORG_ID  # Replace with your Vercel organization ID
        vercel-project-id: YOUR_PROJECT_ID  # Replace with your Vercel project ID
